### ISSUE TITLE
Nothing happened!

### ISSUE THREAD

**Issue by rezamarzban** [peter279k/WebServerDemo#1]
I forked your current repository and I built this, Finally I tested APK with Android device and nothing will be happened!

How do I modify your code to testing it successfully?

**Comment by rezamarzban** [comment]
https://user-images.githubusercontent.com/73051714/212709128-8acd5a7e-5ccf-43a5-b1e2-f9690a6bd6aa.mp4

Here is screen recorder of your app testing

**Comment by peter279k** [comment]
It means the web server and DB server are not started.

As far as I know, I used the Android-NDK to cross compile the PHP, MySQL and Lighttpd for Android.

Their versions are too old and I don't recommend to use them.

If you need to use them, it should let these above of their latest version cross compile for Android firstly.

**Comment by peter279k** [comment]
Maybe you can consider the [reply](https://github.com/proot-me/proot/issues/94#issuecomment-199328114) and use the [GNURootDebian](https://github.com/corbinlc/GNURootDebian) directly.
